export const SHOW_FLOW_PREDICTION_FOR_DAY = 'SHOW_FLOW_PREDICTION_FOR_DAY';
export const FLOW_LOAD_STARTED = 'FLOW_LOAD_STARTED';
export const FLOW_LOAD_SUCCEEDED = 'FLOW_LOAD_SUCCEEDED';
export const PREDICTION_LOAD_STARTED = 'PREDICTION_LOAD_STARTED';
export const PREDICTION_LOAD_SUCCEEDED = 'PREDICTION_LOAD_SUCCEEDED';