export const PROJECT_LOAD_STARTED = 'PROJECT_LOAD_STARTED';
export const PROJECT_LOAD_SUCCEEDED = 'PROJECT_LOAD_SUCCEEDED';
export const SHOW_FLOW_PREDICTION_FOR_DAY = 'SHOW_FLOW_PREDICTION_FOR_DAY';
export const TIME_SERIES_LOAD_STARTED = 'TIME_SERIES_LOAD_STARTED';
export const TIME_SERIES_LOAD_SUCCEEDED = 'TIME_SERIES_LOAD_SUCCEEDED';