export const PROJECT_SELECTED = 'PROJECT_SELECTED';
export const PROJECT_LOAD_STARTED = 'PROJECT_LOAD_STARTED';
export const PROJECT_LOAD_SUCCEEDED = 'PROJECT_LOAD_SUCCEEDED';
export const PROJECT_LOAD_FAILED = 'PROJECT_LOAD_FAILED';