export const PROJECT_SELECTED = 'PROJECT_SELECTED';
export const PROJECT_CONFIGURATION_LOAD_STARTED = 'PROJECT_CONFIGURATION_LOAD_STARTED';
export const PROJECT_CONFIGURATION_LOAD_SUCCEEDED = 'PROJECT_CONFIGURATION_LOAD_SUCCEEDED';